# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a51569e616af2641fe6772dcbc264734678118af663a744639ed97906c6dc6d93ae5cf9884c8e827d281a3f93d31d724074bf4eaf27e4e48a029ae3e30b0554

test:
  secret_key_base: 82e2aec4db68a19ad3131f8582ae194fc59e63c3930cf712392dd8735b07d29823c278097a05c9ac8d920aaaf54bb42f4a849cb081a066ac4ad90703c67733db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
